version: "2"
run:
  relative-path-mode: gomod
output:
  sort-order:
    - linter
    - severity
    - file
linters:
  enable:
    - errcheck
    - copyloopvar
    - cyclop
    - dupl
    - errchkjson
    - errname
    - errorlint
    - forcetypeassert
    - funlen
    - gocognit
    - goconst
    - gocritic
    - godox
    - goheader
    - gosec
    - gosmopolitan
    - iface
    - inamedparam
    - ireturn
    - maintidx
    - misspell
    - mnd
    - nestif
    - nilerr
    - nilnesserr
    - noctx
    - sloglint
    - usestdlibvars
    - loglint
  settings:
    custom:
      loglint:
        type: "module"
        settings:
          cfgPath: ./config.yaml
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - path: plugin\.go
        linters:
          - ireturn
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
